### ISSUE TITLE
عدم اجرای تست

### ISSUE THREAD

**Issue by hlikehamed** [VahidN/DNTScanner.Core#17]
# Summary of the issue

سلام آقای نصیری
من هر کاری کردم موفق نشدم برنامه تست رو اجرا کنم. اگر امکان داره برنامه رو به دات نت 5 به بالا به روز رسانی کنید و یک فایل آموزشی تصویری جهت استفاده در برنامه قرار دهید.

**Comment by hlikehamed** [comment]
ممنون از اینکه ارتقا دادید ولی من همچنان مشکل در اجرای تست دارم. تو نسخه قبلی تونستم خطاها رو برطرف کنم ولی اسکنر روشناسایی نمی کرد. احساس می کنم قسمت سرویس به درستی اجرا نمیشه

**Comment by VahidN** [comment]
- ابتدا درايور اسكنر را نصب كنيد.
- بعد سعي كنيد با استفاده از برنامه‌ي mspaint چيزي را توسط آن اسكن كنيد. اگر موفق شديد، مشكلي نيست.
- سپس [مثال ساده‌ي كنسول](https://github.com/VahidN/DNTScanner.Core/tree/master/DNTScanner.Core.Tests/DNTScanner.ConsoleTestApp) ارائه شده را در ابتدا آزمايش كنيد. اينجا اگر خطايي دريافت كرديد، ارسال كنيد.
