### ISSUE TITLE
Upgrade 3.1 core

### ISSUE THREAD

**Issue by davidbuckleyni** [VahidN/DNTScanner.Core#4]
Hi i would love to use this in app where customers would be uploading documents in via scanners but this is in very old .net core would you upgrade it to .net core 3.1 and using .net core libarys?

**Comment by VahidN** [comment]
You can use a [.NET standard 2](https://github.com/VahidN/DNTScanner.Core/blob/master/DNTScanner.Core/DNTScanner.Core.csproj#L6) library in a .NET Core 3x app.

**Comment by VahidN** [comment]
Upgraded it via#https://github.com/VahidN/DNTScanner.Core/commit/38926c65a3091697c33cd2d2f43ecba92289c1d4
